version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
        MYSQL_ROOT_PASSWORD: root2
        MYSQL_DATABASE: wallet
        MYSQL_USER: root2
        MYSQL_PASSWORD: root2
    ports:
      - "3307:3307"
    volumes:
      - ./.docker/mysql:/var/lib/mysql